version: "3.5"

services:

  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #
  #                                                        #
  # Dataset Handlers                                       #
  #                                                        #
  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #

  # BIOM form handler
  biom-handler:
    image: veupathdb/user-dataset-handler-biom:${BIOME_HANDLER_TAG:-latest}
    networks:
      - internal
      - monitoring-ext
    labels:
      - "com.centurylinklabs.watchtower.enable=${BIOME_HANDLER_WATCHTOWER:-false}"
      - "traefik.enable=false"
      - "prometheus-scrape.enabled=true"

  # Gene list form handler
  gene-list-handler:
    image: veupathdb/user-dataset-handler-gene-list:${GENE_LIST_HANDLER_TAG:-latest}
    networks:
      - internal
      - monitoring-ext
    labels:
      - "com.centurylinklabs.watchtower.enable=${GENE_LIST_HANDLER_WATCHTOWER:-false}"
      - "traefik.enable=false"
      - "prometheus-scrape.enabled=true"

  isasimple-handler:
    image: veupathdb/dataset-handler-isasimple:${ISASIMPLE_HANDLER_TAG:-latest}
    networks:
      - internal
      - monitoring-ext
    labels:
      - "com.centurylinklabs.watchtower.enable=${ISASIMPLE_HANDLER_WATCHTOWER:-false}"
      - "traefik.enable=false"
      - "prometheus-scrape.enabled=true"

  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #
  #                                                        #
  # Import Service                                         #
  #                                                        #
  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #

  # Datastore
  postgres:
    image: veupathdb/user-dataset-import-datastore:${POSTGRES_TAG:-latest}
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - internal
    labels:
      - "com.centurylinklabs.watchtower.enable=${POSTGRES_WATCHTOWER:-false}"
      - "traefik.enable=false"


  # Import Service
  importer:
    image: veupathdb/user-dataset-import-service:${IMPORTER_TAG:-latest}
    networks:
      - internal
      - traefik
      - monitoring-ext
    depends_on:
      - postgres
      - biom-handler
    environment:
      # Server
      SERVER_PORT: ${SERVER_PORT:-80}

      # iRODS Connection Info
      IRODS_HOST: ${IRODS_HOST}
      IRODS_PORT: ${IRODS_PORT}
      IRODS_USER: ${IRODS_USER}
      IRODS_PASS: ${IRODS_PASS}
      IRODS_ZONE: ${IRODS_ZONE}
      IRODS_RESOURCE: ${IRODS_RESOURCE}

      # User token salt
      AUTH_SECRET_KEY: ${AUTH_SECRET_KEY}

      # Account DB Connection Info
      ACCT_DB_USER: ${ACCT_DB_USER}
      ACCT_DB_PASS: ${ACCT_DB_PASS}
      ACCT_DB_TNS_NAME: ${ACCT_DB_TNS_NAME}

      LDAP_SERVER: ${LDAP_SERVER}
      ORACLE_BASE_DN: ${ORACLE_BASE_DN}

      # Postgres settings
      DATASTORE_PASS: ${POSTGRES_PASSWORD}
    command: >-
      sh -c "while ! nc -z ${DB_HOST:-postgres} ${DB_PORT:-5432}; do
        echo 'waiting for postgres';
        sleep 1;
      done;
      java -jar /service.jar"
    labels:
      - "com.centurylinklabs.watchtower.enable=${IMPORTER_WATCHTOWER:-false}"
      - "traefik.http.routers.${TRAEFIK_ROUTER:-udis-dev}.rule=Host(`${TRAEFIK_HOST:-udis-dev.local.apidb.org}`)"
      - "traefik.http.routers.${TRAEFIK_ROUTER:-udis-dev}.tls=true"
      - "traefik.http.routers.${TRAEFIK_ROUTER:-udis-dev}.entrypoints=${TRAEFIK_ENTRYPOINTS:-local}"
      - "traefik.http.services.${TRAEFIK_ROUTER:-udis-dev}.loadbalancer.server.port=${SERVICE_PORT:-80}"
      - "traefik.http.services.${TRAEFIK_ROUTER:-udis-dev}.loadbalancer.passhostheader=${TRAEFIK_PASSHOSTHEADER:-false}"
      - "traefik.docker.network=traefik"
      - "prometheus-scrape.enabled=true"


volumes:
  pg-data:

networks:
  external:
  internal:
    external: false
  traefik:
    external: true
  monitoring-ext:
    external: true
